# Use Node v4 as the base image.
FROM ____________ 

# Add everything in the current directory to our image, in the 'app' folder.
ADD _____________

# Install dependencies
RUN _______________

# Expose our server port.
EXPOSE ______________

# Run our app.
CMD ["node", "/app/index.js"]
